### PR TITLE
[wifi_ddwrt] fix typo

### PR DESCRIPTION
**Pull request by furushchev**
This fix includes:
- add missing `.msg` on import module
- use array module to clarify variable `data` as bytearray
- fix typo `macattr` -> `macaddr`

### CODE REVIEW

**Comment by furushchev** [comment]
ping

**Comment by trainman419** [comment]
This is more than just a typo fix, and deserves a little more explanation.

**Comment by furushchev** [comment]
@trainman419 Sorry for very late response. I updated description of this PR.

**Comment by trainman419** [comment]
Thanks!

**Pull request merged**
