### PR TITLE
updated for focal/noetic/python3 compatibility

### PR DESCRIPTION
**Pull request by davefeilseifer**
upgraded to package format 3, python3 compatibility, passes prerelease tests on noetic/focal:

generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   noetic default ubuntu focal amd64   --custom-repo     wifi_ddrwt__custom-1:git:https://github.com/PR2-prime/wifi_ddwrt.git:noetic-devel   --level 1   --output-dir ./

### CODE REVIEW

**Comment by k-okada** [comment]
@wjwwood @trainman419 @clalancette Could someone give us (@k-okada @davefeilseifer ) for admin permission to this repository and https://github.com/ros-gbp/wifi_ddwrt-release so that we can releases `pr2_robot` to noetic?

**Comment by trainman419** [comment]
Ok, I've granted @k-okada and @davefeilseifer write access to this repository and https://github.com/ros-gbp/wifi_ddwrt-release 

It looks like the changes on this PR aren't backwards compatible and this is targeting the hydro-devel branch. You might want to make a noetic-devel branch and make those changes there instead.

**Comment by k-okada** [comment]
@trainman419 thank you I have created `noetic-devel` branch. Could you set that as default branch ? as well as enable Travis Settings #13 
Anyway releasead into  releasing https://github.com/ros/rosdistro/pull/29470

**Comment by trainman419** [comment]
I've updated the default branch to `noetic-devel` . It looks like Travis is already enabled on this repository but it looks like the repo needs a `.travis.yml` to enable it.

**Comment by k-okada** [comment]
ok, merged https://github.com/ros-drivers/wifi_ddwrt/pull/15 and see if
works -> https://travis-ci.com/github/ros-drivers/wifi_ddwrt

--
◉ Kei Okada



2021年5月11日(火) 6:20 Austin ***@***.***>:

**Pull request merged**
